deleteDependentEntities: true
createMissingRelatedEntities: false
enableMergeEntity: true
resources:
  - kind: komodorService
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .uid
          title: .service
          blueprint: '"komodorService"'
          properties:
            serviceId: .uid
            status: .status
            cluster_name: .cluster
            workload_kind: .kind
            namespace_name: .namespace
            service_name: .service
            link_to_komodor: .link
            labels: .labels
            last_deploy_at: .lastDeploy.endTime | todate
            last_deploy_status: .lastDeploy.status
  - kind: komodorRiskViolations
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .komodorUid
          blueprint: '"komodorRiskViolations"'
          properties:
            status: .status
            komodorUid: .komodorUid
            severity: .severity
            supportingData: .supportingData
            link to komodor: .link
            createdAt: .createdAt | todate
            lastEvalutaedAt: .lastEvaluatedAt | todate
            checkType: .checkType
            workloadType: .komodorUid | split("|") | .[0]
            clusterName: .komodorUid | split("|") | .[1]
            namespaceName: .komodorUid | split("|") | .[2]
            workloadName: .komodorUid | split("|") | .[3]
          relations:
            service:
              combinator: '"and"'
              rules:
                - property: '"workload_kind"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[0]
                - property: '"cluster_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[1]
                - property: '"namespace_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[2]
                - property: '"service_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[3]
  - kind: komodorIssues
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .link | capture("eventId=(?<eventId>[a-f0-9-]+)") | .eventId
          title: .summary
          blueprint: '"komodorIssues"'
          properties:
            details: .details
            status: .status
            startTime: .startTime | todate
            link: .link
            summary: .summary
            type: .type
            workloadName: .summary | split("/") | .[2] | split(" ") | first
            clusterName: .summary | split("/") | .[0]
          relations:
            service:
              combinator: '"and"'
              rules:
                - property: '"service_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[2] | split(" ") | first
                - property: '"cluster_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[0]
                - property: '"namespace_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[1]
