deleteDependentEntities: true
createMissingRelatedEntities: false
enableMergeEntity: true
resources:
  - kind: komodorService
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .uid
          title: .service
          blueprint: '"komodorService"'
          properties:
            service_id: .uid
            status: .status
            cluster_name: .cluster
            workload_kind: .kind
            namespace_name: .namespace
            service_name: .service
            komodor_link: .link
            labels: .labels
            last_deploy_at: .lastDeploy.endTime | todate
            last_deploy_status: .lastDeploy.status
  - kind: komodorRiskViolations
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .komodorUid
          blueprint: '"komodorRiskViolations"'
          properties:
            status: .status
            komodor_uid: .komodorUid
            severity: .severity
            supporting_data: .supportingData
            komodor_link: .link
            created_at: .createdAt | todate
            last_evaluated_at: .lastEvaluatedAt | todate
            check_type: .checkType
            workload_type: .komodorUid | split("|") | .[0]
            cluster_name: .komodorUid | split("|") | .[1]
            namespace_name: .komodorUid | split("|") | .[2]
            workload_name: .komodorUid | split("|") | .[3]
          relations:
            service:
              combinator: '"and"'
              rules:
                - property: '"workload_kind"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[0]
                - property: '"cluster_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[1]
                - property: '"namespace_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[2]
                - property: '"service_name"'
                  operator: '"="'
                  value: .komodorUid | split("|") | .[3]
  - kind: komodorIssues
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .link | capture("eventId=(?<eventId>[a-f0-9-]+)") | .eventId
          title: .summary
          blueprint: '"komodorIssues"'
          properties:
            details: .details
            status: .status
            start_time: .startTime | todate
            komodor_link: .link
            summary: .summary
            type: .type
            workload_name: .summary | split("/") | .[2] | split(" ") | first
            cluster_name: .summary | split("/") | .[0]
          relations:
            service:
              combinator: '"and"'
              rules:
                - property: '"service_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[2] | split(" ") | first
                - property: '"cluster_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[0]
                - property: '"namespace_name"'
                  operator: '"="'
                  value: .summary | split("/") | .[1]
